{
  "openapi": "3.0.0",
  "info": {
    "title": "API da aplicação Booklovers",
    "description": "Documentação da API da aplicação Booklovers",
    "termsOfService": "",
    "version": "0.0.1"
  },
  "servers": [
    {
      "url": "http://localhost:3333",
      "description": "API de teste"
    }
  ],
  "paths": {
    "/users": {
      "post": {
        "summary": "",
        "description": "",
        "tags": [
          "User"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "user": {
                  "value": {
                    "name": "karina",
                    "username": "teste3",
                    "email": "teste3@email.com",
                    "password": "teste#4f",
                    "role_id": "a6150b04-bd4f-4cf6-a1b2-a0efbab720f1"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "msg": "Registro criado"
                }
              }
            }
          },
          "400": {
            "description": "Alguma informação está incorreta como: E-mail já cadastrado ou Username já cadastrado ou Perfil inválido",
            "content": {
              "application/json": {
                "error": "E-mail já cadastrado ou Username já cadastrado ou Perfil inválido"
              }
            }
          },
          "500": {
            "description": "Erro no servidor ou servidor indisponível",
            "content": {
              "application/json": {
                "schema": {
                  "error": "Erro no servidor! Tente mais tarde"
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "",
        "description": "",
        "tags": [
          "User"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "user": {
                  "value": {
                    "id": "9252655d-3361-4910-8f13-9770d5f28ff9",
                    "name": "karinateste",
                    "username": "teste3",
                    "email": "teste3@email.com",
                    "password": "teste#4f",
                    "role_id": "a6150b04-bd4f-4cf6-a1b2-a0efbab720f1"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Alguma informação está incorreta como: E-mail já cadastrado ou Username já cadastrado ou Perfil inválido"
          },
          "403": {
            "description": "Não foi inserido o token"
          },
          "500": {
            "description": "Erro no servidor ou servidor indisponível"
          }
        }
      },
      "get": {
        "summary": "Buscar todos os usuários",
        "description": "Buscar todos os usuários",
        "tags": [
          "User"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "user": {
                  "value": {
                    "id": "9252655d-3361-4910-8f13-9770d5f28ff9",
                    "name": "karinateste",
                    "username": "teste3",
                    "email": "teste3@email.com",
                    "password": "teste#4f",
                    "role_id": "a6150b04-bd4f-4cf6-a1b2-a0efbab720f1"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Alguma informação está incorreta como: E-mail já cadastrado ou Username já cadastrado ou Perfil inválido"
          },
          "403": {
            "description": "Não foi inserido o token"
          },
          "500": {
            "description": "Erro no servidor ou servidor indisponível"
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "summary": "Busca pelo id do usuário",
        "description": "Busca pelo id do usuário",
        "tags": [
          "User"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Buscar usuário pelo id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "username": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Cadastro não encontrado"
          },
          "403": {
            "description": "Não foi inserido o token"
          },
          "500": {
            "description": "Erro no servidor ou servidor indisponível",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "role_id": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}